// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/analizadores/Lexer.flex

package analizadores;

import java_cup.runtime.Symbol;
import reportes.ReporteE;
import reportes.ReporteT;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\2\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\4\21\1\22\1\21"+
    "\1\23\3\21\1\24\1\25\1\26\1\27\1\30\2\0"+
    "\1\31\4\32\1\33\10\32\1\34\1\35\2\32\1\36"+
    "\1\37\6\32\1\0\1\40\2\0\1\32\1\0\1\41"+
    "\1\42\1\43\1\32\1\44\1\45\1\46\1\32\1\47"+
    "\1\32\1\50\1\51\1\52\1\53\1\54\1\55\1\32"+
    "\1\56\1\57\1\60\1\61\1\62\2\32\1\63\1\32"+
    "\1\64\1\65\1\66\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\1\1\16\1\17\1\20\1\21\14\22\1\23\1\1"+
    "\1\24\1\25\1\0\1\26\1\0\1\27\2\0\1\30"+
    "\1\31\1\32\1\33\2\0\1\2\1\0\1\34\1\35"+
    "\1\36\1\37\11\22\1\40\10\22\1\41\1\42\2\0"+
    "\1\43\7\22\1\44\1\22\1\45\1\22\1\46\4\22"+
    "\1\47\1\0\1\2\1\50\2\22\1\51\2\22\1\0"+
    "\1\52\1\53\1\22\1\54\2\22\1\55\1\0\1\56"+
    "\1\22\1\57\1\22\1\0\3\22\1\0\2\22\1\0"+
    "\2\22\1\60\1\61\1\22\1\62\1\0\2\22\1\63"+
    "\13\0\1\64\4\0\1\65\3\0\1\66\4\0\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\67\0\u0113\0\u014a"+
    "\0\67\0\67\0\67\0\u0181\0\67\0\u01b8\0\u01ef\0\u0226"+
    "\0\u025d\0\u0294\0\67\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f"+
    "\0\u0596\0\u05cd\0\67\0\u0604\0\67\0\67\0\334\0\67"+
    "\0\u063b\0\67\0\u0672\0\u06a9\0\67\0\67\0\67\0\67"+
    "\0\u06e0\0\u0717\0\u074e\0\u0785\0\67\0\67\0\67\0\67"+
    "\0\u07bc\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u0370\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe"+
    "\0\u0af5\0\u0b2c\0\67\0\67\0\u0b63\0\u0b9a\0\u0785\0\u0bd1"+
    "\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0370\0\u0d52"+
    "\0\u0370\0\u0d89\0\u0370\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0370"+
    "\0\u0e9c\0\67\0\u0370\0\u0ed3\0\u0f0a\0\u0370\0\u0f41\0\u0f78"+
    "\0\u0faf\0\u0370\0\u0370\0\u0fe6\0\u0370\0\u101d\0\u1054\0\u0370"+
    "\0\u108b\0\u0370\0\u10c2\0\u0370\0\u10f9\0\u1130\0\u1167\0\u119e"+
    "\0\u11d5\0\u120c\0\u1243\0\u127a\0\u12b1\0\u12e8\0\u131f\0\u0370"+
    "\0\67\0\u1356\0\u0370\0\u138d\0\u13c4\0\u13fb\0\u0370\0\u1432"+
    "\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u157c\0\u15b3\0\u15ea"+
    "\0\u1621\0\u1658\0\67\0\u168f\0\u16c6\0\u16fd\0\u1734\0\67"+
    "\0\u176b\0\u17a2\0\u17d9\0\67\0\u1810\0\u1847\0\u187e\0\u18b5"+
    "\0\67";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\3\21\1\22\1\23\1\24\1\25\1\26\7\27\1\2"+
    "\1\27\1\30\1\31\1\32\1\33\1\27\1\34\2\27"+
    "\1\35\1\36\2\27\1\37\1\40\1\41\1\27\1\42"+
    "\1\27\1\43\1\44\1\45\70\0\2\3\113\0\1\46"+
    "\37\0\5\47\1\50\32\47\1\51\26\47\7\0\1\52"+
    "\57\0\10\53\1\0\27\53\1\54\26\53\14\0\1\55"+
    "\12\0\1\56\55\0\1\57\10\0\1\60\75\0\1\61"+
    "\43\0\1\62\4\0\1\63\65\0\1\64\1\0\3\21"+
    "\72\0\1\65\66\0\1\66\66\0\1\67\66\0\1\70"+
    "\60\0\3\27\5\0\7\27\1\0\23\27\24\0\3\27"+
    "\5\0\7\27\1\0\13\27\1\71\1\27\1\72\5\27"+
    "\24\0\3\27\5\0\7\27\1\0\13\27\1\73\7\27"+
    "\24\0\3\27\5\0\7\27\1\0\10\27\1\74\12\27"+
    "\24\0\3\27\5\0\7\27\1\0\1\75\7\27\1\76"+
    "\1\77\1\27\1\100\4\27\1\101\2\27\24\0\3\27"+
    "\5\0\7\27\1\0\4\27\1\102\5\27\1\103\10\27"+
    "\24\0\3\27\5\0\7\27\1\0\1\104\22\27\24\0"+
    "\3\27\5\0\7\27\1\0\6\27\1\105\14\27\24\0"+
    "\3\27\5\0\7\27\1\0\3\27\1\106\14\27\1\107"+
    "\2\27\24\0\3\27\5\0\7\27\1\0\17\27\1\110"+
    "\3\27\24\0\3\27\5\0\7\27\1\0\15\27\1\111"+
    "\5\27\24\0\3\27\5\0\7\27\1\0\1\112\22\27"+
    "\70\0\1\113\6\0\1\47\32\0\1\47\12\0\1\47"+
    "\2\0\1\47\1\0\1\47\16\0\1\114\66\0\1\53"+
    "\27\0\1\53\12\0\1\53\2\0\1\53\1\0\1\53"+
    "\66\0\1\115\6\0\13\62\1\116\53\62\2\63\2\0"+
    "\63\63\21\0\3\117\64\0\3\27\5\0\7\27\1\0"+
    "\13\27\1\120\7\27\24\0\3\27\5\0\7\27\1\0"+
    "\3\27\1\121\17\27\24\0\3\27\5\0\7\27\1\0"+
    "\12\27\1\122\10\27\24\0\3\27\5\0\7\27\1\0"+
    "\16\27\1\123\4\27\24\0\3\27\5\0\7\27\1\0"+
    "\10\27\1\124\12\27\24\0\3\27\5\0\7\27\1\0"+
    "\13\27\1\125\7\27\24\0\3\27\5\0\7\27\1\0"+
    "\17\27\1\126\3\27\24\0\3\27\5\0\7\27\1\0"+
    "\15\27\1\127\5\27\24\0\3\27\5\0\7\27\1\0"+
    "\12\27\1\130\10\27\24\0\3\27\5\0\7\27\1\0"+
    "\17\27\1\131\3\27\24\0\3\27\5\0\7\27\1\0"+
    "\6\27\1\132\14\27\24\0\3\27\5\0\7\27\1\0"+
    "\10\27\1\133\12\27\24\0\3\27\5\0\7\27\1\0"+
    "\4\27\1\134\16\27\24\0\3\27\5\0\7\27\1\0"+
    "\12\27\1\135\10\27\24\0\3\27\5\0\7\27\1\0"+
    "\15\27\1\136\5\27\24\0\3\27\5\0\7\27\1\0"+
    "\20\27\1\137\2\27\24\0\3\27\5\0\7\27\1\0"+
    "\15\27\1\140\5\27\61\0\1\141\10\0\13\62\1\116"+
    "\4\62\1\142\46\62\21\0\3\27\5\0\7\27\1\0"+
    "\10\27\1\143\12\27\24\0\3\27\5\0\7\27\1\0"+
    "\1\144\22\27\24\0\3\27\5\0\7\27\1\0\17\27"+
    "\1\145\3\27\24\0\3\27\5\0\7\27\1\0\3\27"+
    "\1\146\17\27\24\0\3\27\5\0\7\27\1\0\16\27"+
    "\1\147\4\27\24\0\3\27\5\0\7\27\1\0\1\150"+
    "\22\27\22\0\1\151\1\0\3\27\5\0\7\27\1\0"+
    "\23\27\24\0\3\27\5\0\7\27\1\0\2\27\1\152"+
    "\20\27\24\0\3\27\5\0\7\27\1\0\12\27\1\153"+
    "\10\27\24\0\3\27\5\0\7\27\1\0\10\27\1\154"+
    "\12\27\24\0\3\27\5\0\7\27\1\0\3\27\1\155"+
    "\17\27\24\0\3\27\5\0\7\27\1\0\2\27\1\156"+
    "\3\27\1\157\14\27\24\0\3\27\5\0\7\27\1\0"+
    "\3\27\1\160\17\27\52\0\1\161\40\0\3\27\5\0"+
    "\7\27\1\0\7\27\1\162\13\27\24\0\3\27\5\0"+
    "\7\27\1\0\6\27\1\163\14\27\24\0\3\27\5\0"+
    "\7\27\1\0\3\27\1\164\17\27\24\0\3\27\5\0"+
    "\7\27\1\0\17\27\1\165\3\27\40\0\1\166\52\0"+
    "\3\27\5\0\7\27\1\0\3\27\1\167\17\27\24\0"+
    "\3\27\5\0\7\27\1\0\13\27\1\170\7\27\24\0"+
    "\3\27\5\0\7\27\1\0\12\27\1\171\10\27\56\0"+
    "\1\172\34\0\3\27\5\0\7\27\1\0\12\27\1\173"+
    "\10\27\24\0\2\27\1\174\5\0\7\27\1\0\23\27"+
    "\61\0\1\175\31\0\3\27\5\0\7\27\1\0\2\27"+
    "\1\176\20\27\24\0\3\27\5\0\7\27\1\0\12\27"+
    "\1\177\10\27\24\0\3\27\5\0\7\27\1\0\5\27"+
    "\1\200\15\27\51\0\1\201\41\0\3\27\5\0\7\27"+
    "\1\0\20\27\1\202\2\27\24\0\1\27\1\203\1\27"+
    "\5\0\7\27\1\0\23\27\52\0\1\204\40\0\3\27"+
    "\5\0\7\27\1\0\17\27\1\205\3\27\24\0\3\27"+
    "\5\0\7\27\1\0\21\27\1\206\1\27\24\0\3\27"+
    "\5\0\7\27\1\0\3\27\1\207\17\27\56\0\1\210"+
    "\32\0\1\211\1\0\3\27\5\0\7\27\1\0\23\27"+
    "\22\0\1\212\1\0\3\27\5\0\7\27\1\0\23\27"+
    "\63\0\1\213\45\0\1\214\60\0\1\215\3\0\1\216"+
    "\102\0\1\217\100\0\1\220\63\0\1\221\47\0\1\222"+
    "\100\0\1\223\70\0\1\224\65\0\1\225\70\0\1\226"+
    "\54\0\1\227\71\0\1\230\76\0\1\231\43\0\1\232"+
    "\76\0\1\233\67\0\1\234\54\0\1\235\104\0\1\236"+
    "\71\0\1\237\53\0\1\240\105\0\1\241\6\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6380];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\3\11\1\1\1\11"+
    "\5\1\1\11\17\1\1\11\1\1\2\11\1\0\1\11"+
    "\1\0\1\11\2\0\4\11\2\0\1\1\1\0\4\11"+
    "\22\1\2\11\2\0\22\1\1\0\1\11\6\1\1\0"+
    "\7\1\1\0\4\1\1\0\3\1\1\0\2\1\1\0"+
    "\3\1\1\11\2\1\1\0\3\1\13\0\1\11\4\0"+
    "\1\11\3\0\1\11\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[161];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1, yytext());
    }

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { ReporteE.agregarError(
        "LEXICO",
        "Caracter no reconocido: " + yytext(),
        yyline + 1,
        yycolumn + 1
    );
            }
          // fall through
          case 56: break;
          case 2:
            { 
            }
          // fall through
          case 57: break;
          case 3:
            { ReporteT.agregar(yytext(), "NOT", yyline + 1, yycolumn + 1);
                        return symbol(sym.NOT);
            }
          // fall through
          case 58: break;
          case 4:
            { ReporteT.agregar(yytext(), "MOD", yyline + 1, yycolumn + 1);
                        return symbol(sym.MOD);
            }
          // fall through
          case 59: break;
          case 5:
            { ReporteT.agregar(yytext(), "PAR_A", yyline + 1, yycolumn + 1);
                        return symbol(sym.PAR_A);
            }
          // fall through
          case 60: break;
          case 6:
            { ReporteT.agregar(yytext(), "PAR_C", yyline + 1, yycolumn + 1);
                        return symbol(sym.PAR_C);
            }
          // fall through
          case 61: break;
          case 7:
            { ReporteT.agregar(yytext(), "POR", yyline + 1, yycolumn + 1);
                        return symbol(sym.POR);
            }
          // fall through
          case 62: break;
          case 8:
            { ReporteT.agregar(yytext(), "MAS", yyline + 1, yycolumn + 1);
                        return symbol(sym.MAS);
            }
          // fall through
          case 63: break;
          case 9:
            { ReporteT.agregar(yytext(), "COMA", yyline + 1, yycolumn + 1);
                        return symbol(sym.COMA);
            }
          // fall through
          case 64: break;
          case 10:
            { ReporteT.agregar(yytext(), "MENOS", yyline + 1, yycolumn + 1);
                        return symbol(sym.MENOS);
            }
          // fall through
          case 65: break;
          case 11:
            { ReporteT.agregar(yytext(), "PUNTO", yyline + 1, yycolumn + 1);
                        return symbol(sym.PUNTO);
            }
          // fall through
          case 66: break;
          case 12:
            { ReporteT.agregar(yytext(), "DIV", yyline + 1, yycolumn + 1);
                        return symbol(sym.DIV);
            }
          // fall through
          case 67: break;
          case 13:
            { ReporteT.agregar(yytext(), "ENTERO", yyline + 1, yycolumn + 1);
                        return symbol(sym.ENTERO, Integer.parseInt(yytext()));
            }
          // fall through
          case 68: break;
          case 14:
            { ReporteT.agregar(yytext(), "PUNTO_COMA", yyline + 1, yycolumn + 1);
                        return symbol(sym.PUNTO_COMA);
            }
          // fall through
          case 69: break;
          case 15:
            { ReporteT.agregar(yytext(), "MENOR", yyline + 1, yycolumn + 1);
                        return symbol(sym.MENOR);
            }
          // fall through
          case 70: break;
          case 16:
            { ReporteT.agregar(yytext(), "IGUAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.IGUAL);
            }
          // fall through
          case 71: break;
          case 17:
            { ReporteT.agregar(yytext(), "MAYOR", yyline + 1, yycolumn + 1);
                        return symbol(sym.MAYOR);
            }
          // fall through
          case 72: break;
          case 18:
            { ReporteT.agregar(yytext(), "ID", yyline + 1, yycolumn + 1);
                        return symbol(sym.ID, yytext());
            }
          // fall through
          case 73: break;
          case 19:
            { ReporteT.agregar(yytext(), "LLAVE_A", yyline + 1, yycolumn + 1);
                        return symbol(sym.LLAVE_A);
            }
          // fall through
          case 74: break;
          case 20:
            { ReporteT.agregar(yytext(), "LLAVE_C", yyline + 1, yycolumn + 1);
                        return symbol(sym.LLAVE_C);
            }
          // fall through
          case 75: break;
          case 21:
            { ReporteT.agregar(yytext(), "DIFERENTE", yyline + 1, yycolumn + 1);
                        return symbol(sym.DIFERENTE);
            }
          // fall through
          case 76: break;
          case 22:
            { String texto = yytext();
                        texto = texto.substring(1, texto.length() - 1);
                        ReporteT.agregar(yytext(), "CADENA", yyline + 1, yycolumn + 1);
                        return symbol(sym.CADENA, texto);
            }
          // fall through
          case 77: break;
          case 23:
            { ReporteT.agregar(yytext(), "AND", yyline + 1, yycolumn + 1);
                        return symbol(sym.AND);
            }
          // fall through
          case 78: break;
          case 24:
            { ReporteT.agregar(yytext(), "INCREMENTO", yyline + 1, yycolumn + 1);
                         return symbol(sym.INCREMENTO);
            }
          // fall through
          case 79: break;
          case 25:
            { ReporteT.agregar(yytext(), "MAS_IGUAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.MAS_IGUAL);
            }
          // fall through
          case 80: break;
          case 26:
            { ReporteT.agregar(yytext(), "DECREMENTO", yyline + 1, yycolumn + 1);
                        return symbol(sym.DECREMENTO);
            }
          // fall through
          case 81: break;
          case 27:
            { ReporteT.agregar(yytext(), "MENOS_IGUAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.MENOS_IGUAL);
            }
          // fall through
          case 82: break;
          case 28:
            { ReporteT.agregar(yytext(), "DECLARACION", yyline + 1, yycolumn + 1);
                        return symbol(sym.DECLARACION);
            }
          // fall through
          case 83: break;
          case 29:
            { ReporteT.agregar(yytext(), "MENOR_IGUAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.MENOR_IGUAL);
            }
          // fall through
          case 84: break;
          case 30:
            { ReporteT.agregar(yytext(), "IGUAL_IGUAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.IGUAL_IGUAL);
            }
          // fall through
          case 85: break;
          case 31:
            { ReporteT.agregar(yytext(), "MAYOR_IGUAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.MAYOR_IGUAL);
            }
          // fall through
          case 86: break;
          case 32:
            { ReporteT.agregar(yytext(), "IF", yyline + 1, yycolumn + 1);
                        return symbol(sym.IF);
            }
          // fall through
          case 87: break;
          case 33:
            { ReporteT.agregar(yytext(), "OR", yyline + 1, yycolumn + 1);
                        return symbol(sym.OR);
            }
          // fall through
          case 88: break;
          case 34:
            { String texto = yytext();
                        texto = texto.substring(1, texto.length() - 1);
                        ReporteT.agregar(yytext(), "CARACTER", yyline + 1, yycolumn + 1);
                        return symbol(sym.CARACTER, texto);
            }
          // fall through
          case 89: break;
          case 35:
            { ReporteT.agregar(yytext(), "DECIMAL", yyline + 1, yycolumn + 1);
                        return symbol(sym.DECIMAL, Double.parseDouble(yytext()));
            }
          // fall through
          case 90: break;
          case 36:
            { ReporteT.agregar(yytext(), "FOR", yyline + 1, yycolumn + 1);
                        return symbol(sym.FOR);
            }
          // fall through
          case 91: break;
          case 37:
            { ReporteT.agregar(yytext(), "INT", yyline + 1, yycolumn + 1);
                        return symbol(sym.INT);
            }
          // fall through
          case 92: break;
          case 38:
            { ReporteT.agregar(yytext(), "NIL", yyline + 1, yycolumn + 1);
                        return symbol(sym.NIL);
            }
          // fall through
          case 93: break;
          case 39:
            { ReporteT.agregar(yytext(), "VAR", yyline + 1, yycolumn + 1);
                        return symbol(sym.VAR);
            }
          // fall through
          case 94: break;
          case 40:
            { ReporteT.agregar(yytext(), "BOOL", yyline + 1, yycolumn + 1);
                        return symbol(sym.BOOL);
            }
          // fall through
          case 95: break;
          case 41:
            { ReporteT.agregar(yytext(), "ELSE", yyline + 1, yycolumn + 1);
                        return symbol(sym.ELSE);
            }
          // fall through
          case 96: break;
          case 42:
            { ReporteT.agregar(yytext(), "FUNC", yyline + 1, yycolumn + 1);
                        return symbol(sym.FUNC);
            }
          // fall through
          case 97: break;
          case 43:
            { ReporteT.agregar(yytext(), "MAIN", yyline + 1, yycolumn + 1);
                        return symbol(sym.MAIN);
            }
          // fall through
          case 98: break;
          case 44:
            { ReporteT.agregar(yytext(), "RUNE", yyline + 1, yycolumn + 1);
                        return symbol(sym.RUNE);
            }
          // fall through
          case 99: break;
          case 45:
            { ReporteT.agregar(yytext(), "TRUE", yyline + 1, yycolumn + 1);
                        return symbol(sym.TRUE);
            }
          // fall through
          case 100: break;
          case 46:
            { ReporteT.agregar(yytext(), "BREAK", yyline + 1, yycolumn + 1);
                        return symbol(sym.BREAK);
            }
          // fall through
          case 101: break;
          case 47:
            { ReporteT.agregar(yytext(), "FALSE", yyline + 1, yycolumn + 1);
                        return symbol(sym.FALSE);
            }
          // fall through
          case 102: break;
          case 48:
            { ReporteT.agregar(yytext(), "STRING", yyline + 1, yycolumn + 1);
                        return symbol(sym.STRING);
            }
          // fall through
          case 103: break;
          case 49:
            { ReporteT.agregar(yytext(), "DOTSTRING", yyline + 1, yycolumn + 1);
                                return symbol(sym.DOTSTRING);
            }
          // fall through
          case 104: break;
          case 50:
            { ReporteT.agregar(yytext(), "FLOAT64", yyline + 1, yycolumn + 1);
                        return symbol(sym.FLOAT64);
            }
          // fall through
          case 105: break;
          case 51:
            { ReporteT.agregar(yytext(), "CONTINUE", yyline + 1, yycolumn + 1);
                        return symbol(sym.CONTINUE);
            }
          // fall through
          case 106: break;
          case 52:
            { ReporteT.agregar(yytext(), "PRINTLN", yyline + 1, yycolumn + 1);
                                return symbol(sym.PRINTLN);
            }
          // fall through
          case 107: break;
          case 53:
            { ReporteT.agregar(yytext(), "ATOI", yyline + 1, yycolumn + 1);
                                return symbol(sym.ATOI);
            }
          // fall through
          case 108: break;
          case 54:
            { ReporteT.agregar(yytext(), "TYPEOF", yyline + 1, yycolumn + 1);
                                return symbol(sym.TYPEOF);
            }
          // fall through
          case 109: break;
          case 55:
            { ReporteT.agregar(yytext(), "PARSEFLOAT", yyline + 1, yycolumn + 1);
                                return symbol(sym.PARSEFLOAT);
            }
          // fall through
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
