
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package analizadores;

import java.util.LinkedList;
import ast.Instruccion;
import instrucciones.Declaracion;
import instrucciones.Println;
import expresiones.AccVariable;
import expresiones.Operacion;
import instrucciones.If;
import instrucciones.Asignacion;
import instrucciones.For;
import instrucciones.Break;
import instrucciones.Continue;
import instrucciones.Compuesta;
import instrucciones.FuncionNativa;
import java_cup.runtime.Symbol;
import reportes.ReporteE;
import instrucciones.Compuesta;
import instrucciones.Bloque;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20150326 (SVN rev 63) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\107\000\002\002\004\000\002\002\003\000\002\003" +
    "\011\000\002\004\004\000\002\004\002\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003\000\002\005\003\000\002\005\005\000\002" +
    "\005\003\000\002\005\003\000\002\015\004\000\002\016" +
    "\004\000\002\012\007\000\002\012\013\000\002\012\011" +
    "\000\002\012\015\000\002\013\007\000\002\013\013\000" +
    "\002\013\007\000\002\006\007\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\005\000\002\006" +
    "\005\000\002\006\007\000\002\014\005\000\002\014\005" +
    "\000\002\014\005\000\002\014\004\000\002\014\004\000" +
    "\002\011\003\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\007\006\000\002\007" +
    "\006\000\002\017\005\000\002\017\003\000\002\010\005" +
    "\000\002\010\005\000\002\010\005\000\002\010\005\000" +
    "\002\010\005\000\002\010\005\000\002\010\005\000\002" +
    "\010\005\000\002\010\005\000\002\010\005\000\002\010" +
    "\005\000\002\010\005\000\002\010\005\000\002\010\004" +
    "\000\002\010\004\000\002\010\005\000\002\010\006\000" +
    "\002\010\010\000\002\010\011\000\002\010\003\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\010\003\000\002\010\003\000\002\010\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\004\004\004\001\002\000\004\005\010\001" +
    "\002\000\004\002\000\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\056\011\001\002\000" +
    "\004\057\012\001\002\000\004\060\013\001\002\000\024" +
    "\006\ufffd\007\ufffd\011\ufffd\012\ufffd\013\ufffd\024\ufffd\060" +
    "\ufffd\061\ufffd\065\ufffd\001\002\000\024\006\023\007\025" +
    "\011\016\012\033\013\032\024\017\060\024\061\021\065" +
    "\030\001\002\000\024\006\ufffb\007\ufffb\011\ufffb\012\ufffb" +
    "\013\ufffb\024\ufffb\060\ufffb\061\ufffb\065\ufffb\001\002\000" +
    "\042\003\212\006\023\021\052\022\053\023\047\025\055" +
    "\026\050\027\057\036\046\054\060\056\043\065\210\066" +
    "\044\067\061\070\051\071\045\001\002\000\004\056\177" +
    "\001\002\000\024\006\ufffa\007\ufffa\011\ufffa\012\ufffa\013" +
    "\ufffa\024\ufffa\060\ufffa\061\ufffa\065\ufffa\001\002\000\004" +
    "\002\uffff\001\002\000\024\006\ufffe\007\ufffe\011\ufffe\012" +
    "\ufffe\013\ufffe\024\ufffe\060\ufffe\061\ufffe\065\ufffe\001\002" +
    "\000\004\065\165\001\002\000\024\006\ufffd\007\ufffd\011" +
    "\ufffd\012\ufffd\013\ufffd\024\ufffd\060\ufffd\061\ufffd\065\ufffd" +
    "\001\002\000\036\021\052\022\053\023\047\025\055\026" +
    "\050\027\057\036\046\054\060\056\141\065\056\066\044" +
    "\067\061\070\051\071\045\001\002\000\024\006\ufff8\007" +
    "\ufff8\011\ufff8\012\ufff8\013\ufff8\024\ufff8\060\ufff8\061\ufff8" +
    "\065\ufff8\001\002\000\024\006\ufffc\007\ufffc\011\ufffc\012" +
    "\ufffc\013\ufffc\024\ufffc\060\ufffc\061\ufffc\065\ufffc\001\002" +
    "\000\016\031\037\032\040\033\035\034\041\050\042\051" +
    "\036\001\002\000\024\006\ufff7\007\ufff7\011\ufff7\012\ufff7" +
    "\013\ufff7\024\ufff7\060\ufff7\061\ufff7\065\ufff7\001\002\000" +
    "\024\006\ufff4\007\ufff4\011\ufff4\012\ufff4\013\ufff4\024\ufff4" +
    "\060\ufff4\061\ufff4\065\ufff4\001\002\000\024\006\ufff5\007" +
    "\ufff5\011\ufff5\012\ufff5\013\ufff5\024\ufff5\060\ufff5\061\ufff5" +
    "\065\ufff5\001\002\000\024\006\ufff9\007\ufff9\011\ufff9\012" +
    "\ufff9\013\ufff9\024\ufff9\060\ufff9\061\ufff9\065\ufff9\001\002" +
    "\000\036\021\052\022\053\023\047\025\055\026\050\027" +
    "\057\036\046\054\060\056\043\065\056\066\044\067\061" +
    "\070\051\071\045\001\002\000\024\006\ufff2\007\ufff2\011" +
    "\ufff2\012\ufff2\013\ufff2\024\ufff2\060\ufff2\061\ufff2\065\ufff2" +
    "\001\002\000\036\021\052\022\053\023\047\025\055\026" +
    "\050\027\057\036\046\054\060\056\043\065\056\066\044" +
    "\067\061\070\051\071\045\001\002\000\036\021\052\022" +
    "\053\023\047\025\055\026\050\027\057\036\046\054\060" +
    "\056\043\065\056\066\044\067\061\070\051\071\045\001" +
    "\002\000\036\021\052\022\053\023\047\025\055\026\050" +
    "\027\057\036\046\054\060\056\043\065\056\066\044\067" +
    "\061\070\051\071\045\001\002\000\024\006\ufff3\007\ufff3" +
    "\011\ufff3\012\ufff3\013\ufff3\024\ufff3\060\ufff3\061\ufff3\065" +
    "\ufff3\001\002\000\036\021\052\022\053\023\047\025\055" +
    "\026\050\027\057\036\046\054\060\056\043\065\056\066" +
    "\044\067\061\070\051\071\045\001\002\000\064\006\uffc0" +
    "\007\uffc0\011\uffc0\012\uffc0\013\uffc0\024\uffc0\035\uffc0\036" +
    "\uffc0\037\uffc0\040\uffc0\041\uffc0\042\uffc0\043\uffc0\044\uffc0" +
    "\045\uffc0\046\uffc0\047\uffc0\052\uffc0\053\uffc0\057\uffc0\060" +
    "\uffc0\061\uffc0\062\uffc0\063\uffc0\065\uffc0\001\002\000\064" +
    "\006\uffc1\007\uffc1\011\uffc1\012\uffc1\013\uffc1\024\uffc1\035" +
    "\uffc1\036\uffc1\037\uffc1\040\uffc1\041\uffc1\042\uffc1\043\uffc1" +
    "\044\uffc1\045\uffc1\046\uffc1\047\uffc1\052\uffc1\053\uffc1\057" +
    "\uffc1\060\uffc1\061\uffc1\062\uffc1\063\uffc1\065\uffc1\001\002" +
    "\000\036\021\052\022\053\023\047\025\055\026\050\027" +
    "\057\036\046\054\060\056\043\065\056\066\044\067\061" +
    "\070\051\071\045\001\002\000\064\006\uffbc\007\uffbc\011" +
    "\uffbc\012\uffbc\013\uffbc\024\uffbc\035\uffbc\036\uffbc\037\uffbc" +
    "\040\uffbc\041\uffbc\042\uffbc\043\uffbc\044\uffbc\045\uffbc\046" +
    "\uffbc\047\uffbc\052\uffbc\053\uffbc\057\uffbc\060\uffbc\061\uffbc" +
    "\062\uffbc\063\uffbc\065\uffbc\001\002\000\004\056\126\001" +
    "\002\000\064\006\uffc2\007\uffc2\011\uffc2\012\uffc2\013\uffc2" +
    "\024\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2\041\uffc2\042" +
    "\uffc2\043\uffc2\044\uffc2\045\uffc2\046\uffc2\047\uffc2\052\uffc2" +
    "\053\uffc2\057\uffc2\060\uffc2\061\uffc2\062\uffc2\063\uffc2\065" +
    "\uffc2\001\002\000\064\006\uffbe\007\uffbe\011\uffbe\012\uffbe" +
    "\013\uffbe\024\uffbe\035\uffbe\036\uffbe\037\uffbe\040\uffbe\041" +
    "\uffbe\042\uffbe\043\uffbe\044\uffbe\045\uffbe\046\uffbe\047\uffbe" +
    "\052\uffbe\053\uffbe\057\uffbe\060\uffbe\061\uffbe\062\uffbe\063" +
    "\uffbe\065\uffbe\001\002\000\064\006\uffbd\007\uffbd\011\uffbd" +
    "\012\uffbd\013\uffbd\024\uffbd\035\uffbd\036\uffbd\037\uffbd\040" +
    "\uffbd\041\uffbd\042\uffbd\043\uffbd\044\uffbd\045\uffbd\046\uffbd" +
    "\047\uffbd\052\uffbd\053\uffbd\057\uffbd\060\uffbd\061\uffbd\062" +
    "\uffbd\063\uffbd\065\uffbd\001\002\000\060\006\uffe7\007\uffe7" +
    "\011\uffe7\012\uffe7\013\uffe7\024\uffe7\035\072\036\064\037" +
    "\071\040\074\041\070\042\066\043\075\044\065\045\076" +
    "\046\073\047\067\052\063\053\077\060\uffe7\061\uffe7\063" +
    "\uffe7\065\uffe7\001\002\000\004\056\123\001\002\000\064" +
    "\006\uffbb\007\uffbb\011\uffbb\012\uffbb\013\uffbb\024\uffbb\035" +
    "\uffbb\036\uffbb\037\uffbb\040\uffbb\041\uffbb\042\uffbb\043\uffbb" +
    "\044\uffbb\045\uffbb\046\uffbb\047\uffbb\052\uffbb\053\uffbb\057" +
    "\uffbb\060\uffbb\061\uffbb\062\uffbb\063\uffbb\065\uffbb\001\002" +
    "\000\004\056\115\001\002\000\036\021\052\022\053\023" +
    "\047\025\055\026\050\027\057\036\046\054\060\056\043" +
    "\065\056\066\044\067\061\070\051\071\045\001\002\000" +
    "\064\006\uffbf\007\uffbf\011\uffbf\012\uffbf\013\uffbf\024\uffbf" +
    "\035\uffbf\036\uffbf\037\uffbf\040\uffbf\041\uffbf\042\uffbf\043" +
    "\uffbf\044\uffbf\045\uffbf\046\uffbf\047\uffbf\052\uffbf\053\uffbf" +
    "\057\uffbf\060\uffbf\061\uffbf\062\uffbf\063\uffbf\065\uffbf\001" +
    "\002\000\064\006\uffc8\007\uffc8\011\uffc8\012\uffc8\013\uffc8" +
    "\024\uffc8\035\uffc8\036\uffc8\037\uffc8\040\uffc8\041\uffc8\042" +
    "\uffc8\043\uffc8\044\uffc8\045\uffc8\046\uffc8\047\uffc8\052\uffc8" +
    "\053\uffc8\057\uffc8\060\uffc8\061\uffc8\062\uffc8\063\uffc8\065" +
    "\uffc8\001\002\000\036\021\052\022\053\023\047\025\055" +
    "\026\050\027\057\036\046\054\060\056\043\065\056\066" +
    "\044\067\061\070\051\071\045\001\002\000\036\021\052" +
    "\022\053\023\047\025\055\026\050\027\057\036\046\054" +
    "\060\056\043\065\056\066\044\067\061\070\051\071\045" +
    "\001\002\000\036\021\052\022\053\023\047\025\055\026" +
    "\050\027\057\036\046\054\060\056\043\065\056\066\044" +
    "\067\061\070\051\071\045\001\002\000\036\021\052\022" +
    "\053\023\047\025\055\026\050\027\057\036\046\054\060" +
    "\056\043\065\056\066\044\067\061\070\051\071\045\001" +
    "\002\000\036\021\052\022\053\023\047\025\055\026\050" +
    "\027\057\036\046\054\060\056\043\065\056\066\044\067" +
    "\061\070\051\071\045\001\002\000\036\021\052\022\053" +
    "\023\047\025\055\026\050\027\057\036\046\054\060\056" +
    "\043\065\056\066\044\067\061\070\051\071\045\001\002" +
    "\000\036\021\052\022\053\023\047\025\055\026\050\027" +
    "\057\036\046\054\060\056\043\065\056\066\044\067\061" +
    "\070\051\071\045\001\002\000\036\021\052\022\053\023" +
    "\047\025\055\026\050\027\057\036\046\054\060\056\043" +
    "\065\056\066\044\067\061\070\051\071\045\001\002\000" +
    "\036\021\052\022\053\023\047\025\055\026\050\027\057" +
    "\036\046\054\060\056\043\065\056\066\044\067\061\070" +
    "\051\071\045\001\002\000\036\021\052\022\053\023\047" +
    "\025\055\026\050\027\057\036\046\054\060\056\043\065" +
    "\056\066\044\067\061\070\051\071\045\001\002\000\036" +
    "\021\052\022\053\023\047\025\055\026\050\027\057\036" +
    "\046\054\060\056\043\065\056\066\044\067\061\070\051" +
    "\071\045\001\002\000\036\021\052\022\053\023\047\025" +
    "\055\026\050\027\057\036\046\054\060\056\043\065\056" +
    "\066\044\067\061\070\051\071\045\001\002\000\036\021" +
    "\052\022\053\023\047\025\055\026\050\027\057\036\046" +
    "\054\060\056\043\065\056\066\044\067\061\070\051\071" +
    "\045\001\002\000\064\006\uffc9\007\uffc9\011\uffc9\012\uffc9" +
    "\013\uffc9\024\uffc9\035\072\036\064\037\071\040\074\041" +
    "\070\042\066\043\075\044\065\045\076\046\073\047\067" +
    "\052\063\053\uffc9\057\uffc9\060\uffc9\061\uffc9\062\uffc9\063" +
    "\uffc9\065\uffc9\001\002\000\064\006\uffcd\007\uffcd\011\uffcd" +
    "\012\uffcd\013\uffcd\024\uffcd\035\072\036\064\037\071\040" +
    "\074\041\070\042\uffcd\043\uffcd\044\uffcd\045\uffcd\046\uffcd" +
    "\047\uffcd\052\uffcd\053\uffcd\057\uffcd\060\uffcd\061\uffcd\062" +
    "\uffcd\063\uffcd\065\uffcd\001\002\000\064\006\uffcb\007\uffcb" +
    "\011\uffcb\012\uffcb\013\uffcb\024\uffcb\035\072\036\064\037" +
    "\071\040\074\041\070\042\uffcb\043\uffcb\044\065\045\076" +
    "\046\073\047\067\052\uffcb\053\uffcb\057\uffcb\060\uffcb\061" +
    "\uffcb\062\uffcb\063\uffcb\065\uffcb\001\002\000\064\006\uffd2" +
    "\007\uffd2\011\uffd2\012\uffd2\013\uffd2\024\uffd2\035\uffd2\036" +
    "\uffd2\037\uffd2\040\uffd2\041\uffd2\042\uffd2\043\uffd2\044\uffd2" +
    "\045\uffd2\046\uffd2\047\uffd2\052\uffd2\053\uffd2\057\uffd2\060" +
    "\uffd2\061\uffd2\062\uffd2\063\uffd2\065\uffd2\001\002\000\064" +
    "\006\uffd0\007\uffd0\011\uffd0\012\uffd0\013\uffd0\024\uffd0\035" +
    "\072\036\064\037\071\040\074\041\070\042\uffd0\043\uffd0" +
    "\044\uffd0\045\uffd0\046\uffd0\047\uffd0\052\uffd0\053\uffd0\057" +
    "\uffd0\060\uffd0\061\uffd0\062\uffd0\063\uffd0\065\uffd0\001\002" +
    "\000\064\006\uffd5\007\uffd5\011\uffd5\012\uffd5\013\uffd5\024" +
    "\uffd5\035\uffd5\036\uffd5\037\071\040\074\041\070\042\uffd5" +
    "\043\uffd5\044\uffd5\045\uffd5\046\uffd5\047\uffd5\052\uffd5\053" +
    "\uffd5\057\uffd5\060\uffd5\061\uffd5\062\uffd5\063\uffd5\065\uffd5" +
    "\001\002\000\064\006\uffd3\007\uffd3\011\uffd3\012\uffd3\013" +
    "\uffd3\024\uffd3\035\uffd3\036\uffd3\037\uffd3\040\uffd3\041\uffd3" +
    "\042\uffd3\043\uffd3\044\uffd3\045\uffd3\046\uffd3\047\uffd3\052" +
    "\uffd3\053\uffd3\057\uffd3\060\uffd3\061\uffd3\062\uffd3\063\uffd3" +
    "\065\uffd3\001\002\000\064\006\uffd1\007\uffd1\011\uffd1\012" +
    "\uffd1\013\uffd1\024\uffd1\035\uffd1\036\uffd1\037\uffd1\040\uffd1" +
    "\041\uffd1\042\uffd1\043\uffd1\044\uffd1\045\uffd1\046\uffd1\047" +
    "\uffd1\052\uffd1\053\uffd1\057\uffd1\060\uffd1\061\uffd1\062\uffd1" +
    "\063\uffd1\065\uffd1\001\002\000\064\006\uffce\007\uffce\011" +
    "\uffce\012\uffce\013\uffce\024\uffce\035\072\036\064\037\071" +
    "\040\074\041\070\042\uffce\043\uffce\044\uffce\045\uffce\046" +
    "\uffce\047\uffce\052\uffce\053\uffce\057\uffce\060\uffce\061\uffce" +
    "\062\uffce\063\uffce\065\uffce\001\002\000\064\006\uffcc\007" +
    "\uffcc\011\uffcc\012\uffcc\013\uffcc\024\uffcc\035\072\036\064" +
    "\037\071\040\074\041\070\042\uffcc\043\uffcc\044\065\045" +
    "\076\046\073\047\067\052\uffcc\053\uffcc\057\uffcc\060\uffcc" +
    "\061\uffcc\062\uffcc\063\uffcc\065\uffcc\001\002\000\064\006" +
    "\uffcf\007\uffcf\011\uffcf\012\uffcf\013\uffcf\024\uffcf\035\072" +
    "\036\064\037\071\040\074\041\070\042\uffcf\043\uffcf\044" +
    "\uffcf\045\uffcf\046\uffcf\047\uffcf\052\uffcf\053\uffcf\057\uffcf" +
    "\060\uffcf\061\uffcf\062\uffcf\063\uffcf\065\uffcf\001\002\000" +
    "\064\006\uffd4\007\uffd4\011\uffd4\012\uffd4\013\uffd4\024\uffd4" +
    "\035\uffd4\036\uffd4\037\071\040\074\041\070\042\uffd4\043" +
    "\uffd4\044\uffd4\045\uffd4\046\uffd4\047\uffd4\052\uffd4\053\uffd4" +
    "\057\uffd4\060\uffd4\061\uffd4\062\uffd4\063\uffd4\065\uffd4\001" +
    "\002\000\064\006\uffca\007\uffca\011\uffca\012\uffca\013\uffca" +
    "\024\uffca\035\072\036\064\037\071\040\074\041\070\042" +
    "\066\043\075\044\065\045\076\046\073\047\067\052\uffca" +
    "\053\uffca\057\uffca\060\uffca\061\uffca\062\uffca\063\uffca\065" +
    "\uffca\001\002\000\036\021\052\022\053\023\047\025\055" +
    "\026\050\027\057\036\046\054\060\056\043\065\056\066" +
    "\044\067\061\070\051\071\045\001\002\000\036\035\072" +
    "\036\064\037\071\040\074\041\070\042\066\043\075\044" +
    "\065\045\076\046\073\047\067\052\063\053\077\057\117" +
    "\001\002\000\004\030\120\001\002\000\004\056\121\001" +
    "\002\000\004\057\122\001\002\000\064\006\uffc3\007\uffc3" +
    "\011\uffc3\012\uffc3\013\uffc3\024\uffc3\035\uffc3\036\uffc3\037" +
    "\uffc3\040\uffc3\041\uffc3\042\uffc3\043\uffc3\044\uffc3\045\uffc3" +
    "\046\uffc3\047\uffc3\052\uffc3\053\uffc3\057\uffc3\060\uffc3\061" +
    "\uffc3\062\uffc3\063\uffc3\065\uffc3\001\002\000\036\021\052" +
    "\022\053\023\047\025\055\026\050\027\057\036\046\054" +
    "\060\056\043\065\056\066\044\067\061\070\051\071\045" +
    "\001\002\000\036\035\072\036\064\037\071\040\074\041" +
    "\070\042\066\043\075\044\065\045\076\046\073\047\067" +
    "\052\063\053\077\057\125\001\002\000\064\006\uffc5\007" +
    "\uffc5\011\uffc5\012\uffc5\013\uffc5\024\uffc5\035\uffc5\036\uffc5" +
    "\037\uffc5\040\uffc5\041\uffc5\042\uffc5\043\uffc5\044\uffc5\045" +
    "\uffc5\046\uffc5\047\uffc5\052\uffc5\053\uffc5\057\uffc5\060\uffc5" +
    "\061\uffc5\062\uffc5\063\uffc5\065\uffc5\001\002\000\036\021" +
    "\052\022\053\023\047\025\055\026\050\027\057\036\046" +
    "\054\060\056\043\065\056\066\044\067\061\070\051\071" +
    "\045\001\002\000\036\035\072\036\064\037\071\040\074" +
    "\041\070\042\066\043\075\044\065\045\076\046\073\047" +
    "\067\052\063\053\077\062\130\001\002\000\036\021\052" +
    "\022\053\023\047\025\055\026\050\027\057\036\046\054" +
    "\060\056\043\065\056\066\044\067\061\070\051\071\045" +
    "\001\002\000\036\035\072\036\064\037\071\040\074\041" +
    "\070\042\066\043\075\044\065\045\076\046\073\047\067" +
    "\052\063\053\077\057\132\001\002\000\064\006\uffc4\007" +
    "\uffc4\011\uffc4\012\uffc4\013\uffc4\024\uffc4\035\uffc4\036\uffc4" +
    "\037\uffc4\040\uffc4\041\uffc4\042\uffc4\043\uffc4\044\uffc4\045" +
    "\uffc4\046\uffc4\047\uffc4\052\uffc4\053\uffc4\057\uffc4\060\uffc4" +
    "\061\uffc4\062\uffc4\063\uffc4\065\uffc4\001\002\000\064\006" +
    "\uffc7\007\uffc7\011\uffc7\012\uffc7\013\uffc7\024\uffc7\035\uffc7" +
    "\036\uffc7\037\uffc7\040\uffc7\041\uffc7\042\uffc7\043\uffc7\044" +
    "\uffc7\045\uffc7\046\uffc7\047\uffc7\052\uffc7\053\uffc7\057\uffc7" +
    "\060\uffc7\061\uffc7\062\uffc7\063\uffc7\065\uffc7\001\002\000" +
    "\036\035\072\036\064\037\071\040\074\041\070\042\066" +
    "\043\075\044\065\045\076\046\073\047\067\052\063\053" +
    "\077\057\135\001\002\000\064\006\uffc6\007\uffc6\011\uffc6" +
    "\012\uffc6\013\uffc6\024\uffc6\035\uffc6\036\uffc6\037\uffc6\040" +
    "\uffc6\041\uffc6\042\uffc6\043\uffc6\044\uffc6\045\uffc6\046\uffc6" +
    "\047\uffc6\052\uffc6\053\uffc6\057\uffc6\060\uffc6\061\uffc6\062" +
    "\uffc6\063\uffc6\065\uffc6\001\002\000\060\006\uffe6\007\uffe6" +
    "\011\uffe6\012\uffe6\013\uffe6\024\uffe6\035\072\036\064\037" +
    "\071\040\074\041\070\042\066\043\075\044\065\045\076" +
    "\046\073\047\067\052\063\053\077\060\uffe6\061\uffe6\063" +
    "\uffe6\065\uffe6\001\002\000\060\006\uffe8\007\uffe8\011\uffe8" +
    "\012\uffe8\013\uffe8\024\uffe8\035\072\036\064\037\071\040" +
    "\074\041\070\042\066\043\075\044\065\045\076\046\073" +
    "\047\067\052\063\053\077\060\uffe8\061\uffe8\063\uffe8\065" +
    "\uffe8\001\002\000\060\006\uffe5\007\uffe5\011\uffe5\012\uffe5" +
    "\013\uffe5\024\uffe5\035\072\036\064\037\071\040\074\041" +
    "\070\042\066\043\075\044\065\045\076\046\073\047\067" +
    "\052\063\053\077\060\uffe5\061\uffe5\063\uffe5\065\uffe5\001" +
    "\002\000\040\003\152\021\052\022\053\023\047\025\055" +
    "\026\050\027\057\036\046\054\060\056\043\065\056\066" +
    "\044\067\061\070\051\071\045\001\002\000\036\035\072" +
    "\036\064\037\071\040\074\041\070\042\066\043\075\044" +
    "\065\045\076\046\073\047\067\052\063\053\077\060\143" +
    "\001\002\000\024\006\ufffd\007\ufffd\011\ufffd\012\ufffd\013" +
    "\ufffd\024\ufffd\060\ufffd\061\ufffd\065\ufffd\001\002\000\024" +
    "\006\023\007\025\011\016\012\033\013\032\024\017\060" +
    "\024\061\145\065\030\001\002\000\026\006\ufff1\007\ufff1" +
    "\010\146\011\ufff1\012\ufff1\013\ufff1\024\ufff1\060\ufff1\061" +
    "\ufff1\065\ufff1\001\002\000\004\060\147\001\002\000\024" +
    "\006\ufffd\007\ufffd\011\ufffd\012\ufffd\013\ufffd\024\ufffd\060" +
    "\ufffd\061\ufffd\065\ufffd\001\002\000\024\006\023\007\025" +
    "\011\016\012\033\013\032\024\017\060\024\061\151\065" +
    "\030\001\002\000\024\006\ufff0\007\ufff0\011\ufff0\012\ufff0" +
    "\013\ufff0\024\ufff0\060\ufff0\061\ufff0\065\ufff0\001\002\000" +
    "\004\057\153\001\002\000\004\060\154\001\002\000\024" +
    "\006\ufffd\007\ufffd\011\ufffd\012\ufffd\013\ufffd\024\ufffd\060" +
    "\ufffd\061\ufffd\065\ufffd\001\002\000\024\006\023\007\025" +
    "\011\016\012\033\013\032\024\017\060\024\061\156\065" +
    "\030\001\002\000\026\006\uffef\007\uffef\010\157\011\uffef" +
    "\012\uffef\013\uffef\024\uffef\060\uffef\061\uffef\065\uffef\001" +
    "\002\000\004\060\160\001\002\000\024\006\ufffd\007\ufffd" +
    "\011\ufffd\012\ufffd\013\ufffd\024\ufffd\060\ufffd\061\ufffd\065" +
    "\ufffd\001\002\000\024\006\023\007\025\011\016\012\033" +
    "\013\032\024\017\060\024\061\162\065\030\001\002\000" +
    "\024\006\uffee\007\uffee\011\uffee\012\uffee\013\uffee\024\uffee" +
    "\060\uffee\061\uffee\065\uffee\001\002\000\024\006\023\007" +
    "\025\011\016\012\033\013\032\024\017\060\024\061\164" +
    "\065\030\001\002\000\024\006\ufff6\007\ufff6\011\ufff6\012" +
    "\ufff6\013\ufff6\024\ufff6\060\ufff6\061\ufff6\065\ufff6\001\002" +
    "\000\014\014\173\015\172\016\166\017\171\020\170\001" +
    "\002\000\030\006\uffdc\007\uffdc\011\uffdc\012\uffdc\013\uffdc" +
    "\024\uffdc\034\uffdc\060\uffdc\061\uffdc\063\uffdc\065\uffdc\001" +
    "\002\000\030\006\uffe9\007\uffe9\011\uffe9\012\uffe9\013\uffe9" +
    "\024\uffe9\034\174\060\uffe9\061\uffe9\063\uffe9\065\uffe9\001" +
    "\002\000\030\006\uffda\007\uffda\011\uffda\012\uffda\013\uffda" +
    "\024\uffda\034\uffda\060\uffda\061\uffda\063\uffda\065\uffda\001" +
    "\002\000\030\006\uffdb\007\uffdb\011\uffdb\012\uffdb\013\uffdb" +
    "\024\uffdb\034\uffdb\060\uffdb\061\uffdb\063\uffdb\065\uffdb\001" +
    "\002\000\030\006\uffdd\007\uffdd\011\uffdd\012\uffdd\013\uffdd" +
    "\024\uffdd\034\uffdd\060\uffdd\061\uffdd\063\uffdd\065\uffdd\001" +
    "\002\000\030\006\uffde\007\uffde\011\uffde\012\uffde\013\uffde" +
    "\024\uffde\034\uffde\060\uffde\061\uffde\063\uffde\065\uffde\001" +
    "\002\000\040\003\176\021\052\022\053\023\047\025\055" +
    "\026\050\027\057\036\046\054\060\056\043\065\056\066" +
    "\044\067\061\070\051\071\045\001\002\000\060\006\uffea" +
    "\007\uffea\011\uffea\012\uffea\013\uffea\024\uffea\035\072\036" +
    "\064\037\071\040\074\041\070\042\066\043\075\044\065" +
    "\045\076\046\073\047\067\052\063\053\077\060\uffea\061" +
    "\uffea\063\uffea\065\uffea\001\002\000\026\006\uffe4\007\uffe4" +
    "\011\uffe4\012\uffe4\013\uffe4\024\uffe4\060\uffe4\061\uffe4\063" +
    "\uffe4\065\uffe4\001\002\000\040\003\202\021\052\022\053" +
    "\023\047\025\055\026\050\027\057\036\046\054\060\056" +
    "\043\065\056\066\044\067\061\070\051\071\045\001\002" +
    "\000\006\057\205\062\204\001\002\000\040\035\072\036" +
    "\064\037\071\040\074\041\070\042\066\043\075\044\065" +
    "\045\076\046\073\047\067\052\063\053\077\057\uffd6\062" +
    "\uffd6\001\002\000\004\057\203\001\002\000\024\006\uffd8" +
    "\007\uffd8\011\uffd8\012\uffd8\013\uffd8\024\uffd8\060\uffd8\061" +
    "\uffd8\065\uffd8\001\002\000\036\021\052\022\053\023\047" +
    "\025\055\026\050\027\057\036\046\054\060\056\043\065" +
    "\056\066\044\067\061\070\051\071\045\001\002\000\024" +
    "\006\uffd9\007\uffd9\011\uffd9\012\uffd9\013\uffd9\024\uffd9\060" +
    "\uffd9\061\uffd9\065\uffd9\001\002\000\040\035\072\036\064" +
    "\037\071\040\074\041\070\042\066\043\075\044\065\045" +
    "\076\046\073\047\067\052\063\053\077\057\uffd7\062\uffd7" +
    "\001\002\000\036\035\072\036\064\037\071\040\074\041" +
    "\070\042\066\043\075\044\065\045\076\046\073\047\067" +
    "\052\063\053\077\060\236\001\002\000\046\031\037\032" +
    "\040\033\035\034\041\035\uffbb\036\uffbb\037\uffbb\040\uffbb" +
    "\041\uffbb\042\uffbb\043\uffbb\044\uffbb\045\uffbb\046\uffbb\047" +
    "\uffbb\052\uffbb\053\uffbb\060\uffbb\001\002\000\004\063\216" +
    "\001\002\000\004\060\213\001\002\000\024\006\ufffd\007" +
    "\ufffd\011\ufffd\012\ufffd\013\ufffd\024\ufffd\060\ufffd\061\ufffd" +
    "\065\ufffd\001\002\000\024\006\023\007\025\011\016\012" +
    "\033\013\032\024\017\060\024\061\215\065\030\001\002" +
    "\000\024\006\uffeb\007\uffeb\011\uffeb\012\uffeb\013\uffeb\024" +
    "\uffeb\060\uffeb\061\uffeb\065\uffeb\001\002\000\036\021\052" +
    "\022\053\023\047\025\055\026\050\027\057\036\046\054" +
    "\060\056\043\065\056\066\044\067\061\070\051\071\045" +
    "\001\002\000\036\035\072\036\064\037\071\040\074\041" +
    "\070\042\066\043\075\044\065\045\076\046\073\047\067" +
    "\052\063\053\077\063\220\001\002\000\004\065\221\001" +
    "\002\000\014\032\230\033\226\034\231\050\232\051\227" +
    "\001\002\000\004\060\223\001\002\000\024\006\ufffd\007" +
    "\ufffd\011\ufffd\012\ufffd\013\ufffd\024\ufffd\060\ufffd\061\ufffd" +
    "\065\ufffd\001\002\000\024\006\023\007\025\011\016\012" +
    "\033\013\032\024\017\060\024\061\225\065\030\001\002" +
    "\000\024\006\uffec\007\uffec\011\uffec\012\uffec\013\uffec\024" +
    "\uffec\060\uffec\061\uffec\065\uffec\001\002\000\036\021\052" +
    "\022\053\023\047\025\055\026\050\027\057\036\046\054" +
    "\060\056\043\065\056\066\044\067\061\070\051\071\045" +
    "\001\002\000\004\060\uffdf\001\002\000\036\021\052\022" +
    "\053\023\047\025\055\026\050\027\057\036\046\054\060" +
    "\056\043\065\056\066\044\067\061\070\051\071\045\001" +
    "\002\000\036\021\052\022\053\023\047\025\055\026\050" +
    "\027\057\036\046\054\060\056\043\065\056\066\044\067" +
    "\061\070\051\071\045\001\002\000\004\060\uffe0\001\002" +
    "\000\036\035\072\036\064\037\071\040\074\041\070\042" +
    "\066\043\075\044\065\045\076\046\073\047\067\052\063" +
    "\053\077\060\uffe1\001\002\000\036\035\072\036\064\037" +
    "\071\040\074\041\070\042\066\043\075\044\065\045\076" +
    "\046\073\047\067\052\063\053\077\060\uffe3\001\002\000" +
    "\036\035\072\036\064\037\071\040\074\041\070\042\066" +
    "\043\075\044\065\045\076\046\073\047\067\052\063\053" +
    "\077\060\uffe2\001\002\000\024\006\ufffd\007\ufffd\011\ufffd" +
    "\012\ufffd\013\ufffd\024\ufffd\060\ufffd\061\ufffd\065\ufffd\001" +
    "\002\000\024\006\023\007\025\011\016\012\033\013\032" +
    "\024\017\060\024\061\240\065\030\001\002\000\024\006" +
    "\uffed\007\uffed\011\uffed\012\uffed\013\uffed\024\uffed\060\uffed" +
    "\061\uffed\065\uffed\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\236\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\013\001\001\000\020\005\021\006\026\007\014" +
    "\012\017\013\033\015\025\016\030\001\001\000\002\001" +
    "\001\000\006\006\210\010\206\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\162\001\001\000\004\010\141" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\010\137\001\001\000\002\001" +
    "\001\000\004\010\136\001\001\000\004\010\135\001\001" +
    "\000\004\010\053\001\001\000\002\001\001\000\004\010" +
    "\133\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\010\132\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\010\061\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\113\001\001\000\004\010\112\001" +
    "\001\000\004\010\111\001\001\000\004\010\110\001\001" +
    "\000\004\010\107\001\001\000\004\010\106\001\001\000" +
    "\004\010\105\001\001\000\004\010\104\001\001\000\004" +
    "\010\103\001\001\000\004\010\102\001\001\000\004\010" +
    "\101\001\001\000\004\010\100\001\001\000\004\010\077" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\115\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\123\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\010\126\001\001\000\002\001\001" +
    "\000\004\010\130\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\133\001\001\000\002\001\001\000\004\004\143" +
    "\001\001\000\020\005\021\006\026\007\014\012\017\013" +
    "\033\015\025\016\030\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\004\147\001\001\000\020\005\021\006" +
    "\026\007\014\012\017\013\033\015\025\016\030\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\154\001\001\000\020\005\021\006\026\007\014" +
    "\012\017\013\033\015\025\016\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\004\160\001\001\000\020" +
    "\005\021\006\026\007\014\012\017\013\033\015\025\016" +
    "\030\001\001\000\002\001\001\000\020\005\021\006\026" +
    "\007\014\012\017\013\033\015\025\016\030\001\001\000" +
    "\002\001\001\000\004\011\166\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\010\174\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\200\017" +
    "\177\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\205\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\213\001\001\000\020\005\021\006\026\007\014\012\017" +
    "\013\033\015\025\016\030\001\001\000\002\001\001\000" +
    "\004\010\216\001\001\000\002\001\001\000\004\014\221" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\223\001\001\000\020\005\021\006\026\007\014\012\017" +
    "\013\033\015\025\016\030\001\001\000\002\001\001\000" +
    "\004\010\234\001\001\000\002\001\001\000\004\010\233" +
    "\001\001\000\004\010\232\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\236\001\001\000\020\005\021\006\026\007\014\012" +
    "\017\013\033\015\025\016\030\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    @Override
    public void syntax_error(java_cup.runtime.Symbol s) {
        //ReporteE.agregarError(
        //    "SINTACTICO",
        //    "Error sintáctico cerca de: " + s.value,
        //    s.left,
        //    s.right
        //);
    }

    @Override
    public void unrecovered_syntax_error(java_cup.runtime.Symbol s) throws Exception {
        ReporteE.agregarError(
            "SINTACTICO",
            "No se pudo recuperar del error sintáctico cerca de: " + s.value,
            s.left,
            s.right
        );
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> start_val = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= funcion_main 
            {
              LinkedList<Instruccion> RESULT =null;
		int fmleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fmright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		LinkedList<Instruccion> fm = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = fm; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // funcion_main ::= FUNC MAIN PAR_A PAR_C LLAVE_A instrucciones LLAVE_C 
            {
              LinkedList<Instruccion> RESULT =null;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = ins; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion_main",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // instrucciones ::= instrucciones instruccion 
            {
              LinkedList<Instruccion> RESULT =null;
		int listaleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int listaright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> lista = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion ins = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                    if (ins != null) {
                        lista.add(ins);
                    }
                    RESULT = lista;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instrucciones ::= 
            {
              LinkedList<Instruccion> RESULT =null;
		
                    RESULT = new LinkedList<Instruccion>();
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instrucciones",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= declaracion 
            {
              Instruccion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion d = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= impresion 
            {
              Instruccion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instruccion ::= if_instr 
            {
              Instruccion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= for_instr 
            {
              Instruccion RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion f = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = f; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= incremento 
            {
              Instruccion RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion i = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = i; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= decremento 
            {
              Instruccion RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Instruccion d = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = d; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> l = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                  RESULT = new Bloque(l);
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= BREAK 
            {
              Instruccion RESULT =null;
		 RESULT = new Break(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instruccion ::= CONTINUE 
            {
              Instruccion RESULT =null;
		 RESULT = new Continue(); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("instruccion",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // incremento ::= ID INCREMENTO 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    RESULT = new Compuesta(id, 1, "+");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("incremento",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // decremento ::= ID DECREMENTO 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
    RESULT = new Compuesta(id, 1, "-");

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decremento",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // if_instr ::= IF expresion LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object condicion = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                RESULT = new If(condicion, ins, null);
             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_instr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // if_instr ::= IF expresion LLAVE_A instrucciones LLAVE_C ELSE LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Object condicion = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int ins_ifleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int ins_ifright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		LinkedList<Instruccion> ins_if = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int ins_elseleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ins_elseright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins_else = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                RESULT = new If(condicion, ins_if, ins_else);
             
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_instr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // if_instr ::= IF PAR_A error PAR_C LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    ReporteE.agregarError(
                        "SINTACTICO",
                        "Condición inválida dentro del if",
                        0,
                        0
                    );

                    RESULT = null;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_instr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // if_instr ::= IF PAR_A error PAR_C LLAVE_A instrucciones LLAVE_C ELSE LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int ins_ifleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int ins_ifright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		LinkedList<Instruccion> ins_if = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int ins_elseleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int ins_elseright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins_else = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                     ReporteE.agregarError(
                         "SINTACTICO",
                         "Condición inválida dentro del if",
                         0,
                         0
                     );

                     RESULT = null;
                 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_instr",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // for_instr ::= FOR expresion LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object condicion = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    RESULT = new For(null, condicion, null, ins);
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_instr",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // for_instr ::= FOR declaracion PUNTO_COMA expresion PUNTO_COMA actualizacion_for LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int inicioleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int inicioright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		Instruccion inicio = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int condicionleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int condicionright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		Object condicion = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		int actualizacionleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int actualizacionright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Instruccion actualizacion = (Instruccion)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                  RESULT = new For(inicio, condicion, actualizacion, ins);
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_instr",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // for_instr ::= FOR error LLAVE_A instrucciones LLAVE_C 
            {
              Instruccion RESULT =null;
		int insleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int insright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Instruccion> ins = (LinkedList<Instruccion>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                    ReporteE.agregarError(
                        "SINTACTICO",
                        "Condición inválida dentro del for",
                        0,
                        0
                    );

                    RESULT = null;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_instr",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracion ::= VAR ID tipo IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  RESULT = new Declaracion(id, t, e);
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // declaracion ::= VAR ID tipo 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  RESULT = new Declaracion(id, t, null);
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // declaracion ::= ID DECLARACION expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  String tipoInferido = "desconocido";

                  if (e instanceof Integer) tipoInferido = "int";
                  else if (e instanceof Double) tipoInferido = "float64";
                  else if (e instanceof String) tipoInferido = "string";
                  else if (e instanceof Boolean) tipoInferido = "bool";

                  RESULT = new Declaracion(id, tipoInferido, e);
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // declaracion ::= ID IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  RESULT = new Asignacion(id, e);
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // declaracion ::= ID MAS_IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  RESULT = new Compuesta(id, e, "+");
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracion ::= ID MENOS_IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                  RESULT = new Compuesta(id, e, "-");
              
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declaracion ::= VAR ID tipo IGUAL error 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		
                    ReporteE.agregarError(
                        "SINTACTICO",
                        "Se esperaba una expresión después del '=' en la declaración de '" + id + "'",
                        0,
                        0
                    );

                    RESULT = null;
                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("declaracion",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // actualizacion_for ::= ID MAS_IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int valorleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object valor = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                          RESULT = new Compuesta(id, valor,"+");
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion_for",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // actualizacion_for ::= ID MENOS_IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int valorleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object valor = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                          RESULT = new Compuesta(id, valor,"-");
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion_for",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // actualizacion_for ::= ID IGUAL expresion 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int valorleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object valor = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
                          RESULT = new Asignacion(id, valor);
                      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion_for",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // actualizacion_for ::= ID INCREMENTO 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Compuesta(id, 1, "++"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion_for",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // actualizacion_for ::= ID DECREMENTO 
            {
              Instruccion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new Compuesta(id, 1, "--"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("actualizacion_for",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipo ::= INT 
            {
              String RESULT =null;
		 RESULT = "int"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // tipo ::= FLOAT64 
            {
              String RESULT =null;
		 RESULT = "float64"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // tipo ::= STRING 
            {
              String RESULT =null;
		 RESULT = "string"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // tipo ::= BOOL 
            {
              String RESULT =null;
		 RESULT = "bool"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // tipo ::= RUNE 
            {
              String RESULT =null;
		 RESULT = "rune"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // impresion ::= PRINTLN PAR_A lista_print PAR_C 
            {
              Instruccion RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		LinkedList<Object> e = (LinkedList<Object>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                RESULT = new Println(e);
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // impresion ::= PRINTLN PAR_A error PAR_C 
            {
              Instruccion RESULT =null;
		
                ReporteE.agregarError(
                    "SINTACTICO",
                    "Expresión inválida dentro de fmt.Println",
                    0,
                    0
                );

                RESULT = null;
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("impresion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_print ::= lista_print COMA expresion 
            {
              LinkedList<Object> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		LinkedList<Object> l = (LinkedList<Object>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          l.add(e);
          RESULT = l;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_print",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lista_print ::= expresion 
            {
              LinkedList<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		
          LinkedList<Object> lista = new LinkedList<Object>();
          lista.add(e);
          RESULT = lista;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_print",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion ::= expresion MAS expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "+"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion ::= expresion MENOS expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "-"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= expresion POR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "*"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= expresion DIV expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "/"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= expresion MOD expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "%"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= expresion MAYOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, ">"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= expresion MENOR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "<"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= expresion MAYOR_IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, ">="); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= expresion MENOR_IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "<="); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= expresion IGUAL_IGUAL expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "=="); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= expresion DIFERENTE expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "!="); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= expresion AND expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "&&"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e1, e2, "||"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresion ::= NOT expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(e, null, "!"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresion ::= MENOS expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new Operacion(0, e, "-"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresion ::= PAR_A expresion PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresion ::= ATOI PAR_A expresion PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                RESULT = new FuncionNativa("atoi", e);
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresion ::= PARSEFLOAT PAR_A expresion COMA expresion PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
                RESULT = new FuncionNativa("parsefloat", e);
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresion ::= TYPEOF PAR_A expresion PAR_C DOTSTRING PAR_A PAR_C 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		
                RESULT = new FuncionNativa("typeof", e);
            
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresion ::= ENTERO 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Integer e = (Integer)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresion ::= DECIMAL 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expresion ::= CADENA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= CARACTER 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = e; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = true; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = false; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= NIL 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new AccVariable(id); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
